/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UniversityCourse } from "./UniversityCourse";
export type { YCToken } from "./YCToken";
export * as factories from "./factories";
export { UniversityCourse__factory } from "./factories/UniversityCourse__factory";
export { YCToken__factory } from "./factories/YCToken__factory";
