/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace UniversityCourse {
  export type CourseStruct = {
    id: BigNumberish;
    title: string;
    description: string;
    coverUrl: string;
    priceYCT: BigNumberish;
    instructor: AddressLike;
    isActive: boolean;
    createdAt: BigNumberish;
    totalStudents: BigNumberish;
  };

  export type CourseStructOutput = [
    id: bigint,
    title: string,
    description: string,
    coverUrl: string,
    priceYCT: bigint,
    instructor: string,
    isActive: boolean,
    createdAt: bigint,
    totalStudents: bigint
  ] & {
    id: bigint;
    title: string;
    description: string;
    coverUrl: string;
    priceYCT: bigint;
    instructor: string;
    isActive: boolean;
    createdAt: bigint;
    totalStudents: bigint;
  };
}

export interface UniversityCourseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "courseCounter"
      | "courses"
      | "createCourse"
      | "deactivateCourse"
      | "getActiveCourses"
      | "getCourse"
      | "getInstructorCourses"
      | "getStudentCourses"
      | "hasPurchased"
      | "hasUserPurchased"
      | "instructorCourses"
      | "owner"
      | "platformFeePercent"
      | "purchaseCourse"
      | "renounceOwnership"
      | "setPlatformFee"
      | "studentCourses"
      | "transferOwnership"
      | "updateCourse"
      | "ycToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CourseCreated"
      | "CourseDeactivated"
      | "CoursePurchased"
      | "CourseUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "courseCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCourse",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateCourse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveCourses",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstructorCourses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentCourses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserPurchased",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "instructorCourses",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCourse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "studentCourses",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCourse",
    values: [BigNumberish, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ycToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "courseCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCourse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInstructorCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "instructorCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ycToken", data: BytesLike): Result;
}

export namespace CourseCreatedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    title: string,
    instructor: AddressLike,
    priceYCT: BigNumberish
  ];
  export type OutputTuple = [
    courseId: bigint,
    title: string,
    instructor: string,
    priceYCT: bigint
  ];
  export interface OutputObject {
    courseId: bigint;
    title: string;
    instructor: string;
    priceYCT: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseDeactivatedEvent {
  export type InputTuple = [courseId: BigNumberish];
  export type OutputTuple = [courseId: bigint];
  export interface OutputObject {
    courseId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoursePurchasedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    student: AddressLike,
    priceYCT: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    courseId: bigint,
    student: string,
    priceYCT: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    courseId: bigint;
    student: string;
    priceYCT: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseUpdatedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    title: string,
    priceYCT: BigNumberish
  ];
  export type OutputTuple = [courseId: bigint, title: string, priceYCT: bigint];
  export interface OutputObject {
    courseId: bigint;
    title: string;
    priceYCT: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UniversityCourse extends BaseContract {
  connect(runner?: ContractRunner | null): UniversityCourse;
  waitForDeployment(): Promise<this>;

  interface: UniversityCourseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  courseCounter: TypedContractMethod<[], [bigint], "view">;

  courses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        title: string;
        description: string;
        coverUrl: string;
        priceYCT: bigint;
        instructor: string;
        isActive: boolean;
        createdAt: bigint;
        totalStudents: bigint;
      }
    ],
    "view"
  >;

  createCourse: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _coverUrl: string,
      _priceYCT: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deactivateCourse: TypedContractMethod<
    [_courseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveCourses: TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [UniversityCourse.CourseStructOutput[]],
    "view"
  >;

  getCourse: TypedContractMethod<
    [_courseId: BigNumberish],
    [UniversityCourse.CourseStructOutput],
    "view"
  >;

  getInstructorCourses: TypedContractMethod<
    [_instructor: AddressLike],
    [bigint[]],
    "view"
  >;

  getStudentCourses: TypedContractMethod<
    [_student: AddressLike],
    [bigint[]],
    "view"
  >;

  hasPurchased: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasUserPurchased: TypedContractMethod<
    [_courseId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;

  instructorCourses: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  purchaseCourse: TypedContractMethod<
    [_courseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPlatformFee: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  studentCourses: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCourse: TypedContractMethod<
    [
      _courseId: BigNumberish,
      _title: string,
      _description: string,
      _coverUrl: string,
      _priceYCT: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  ycToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "courseCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "courses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        title: string;
        description: string;
        coverUrl: string;
        priceYCT: bigint;
        instructor: string;
        isActive: boolean;
        createdAt: bigint;
        totalStudents: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCourse"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _coverUrl: string,
      _priceYCT: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateCourse"
  ): TypedContractMethod<[_courseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveCourses"
  ): TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [UniversityCourse.CourseStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCourse"
  ): TypedContractMethod<
    [_courseId: BigNumberish],
    [UniversityCourse.CourseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInstructorCourses"
  ): TypedContractMethod<[_instructor: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getStudentCourses"
  ): TypedContractMethod<[_student: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserPurchased"
  ): TypedContractMethod<
    [_courseId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "instructorCourses"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseCourse"
  ): TypedContractMethod<[_courseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "studentCourses"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCourse"
  ): TypedContractMethod<
    [
      _courseId: BigNumberish,
      _title: string,
      _description: string,
      _coverUrl: string,
      _priceYCT: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ycToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CourseCreated"
  ): TypedContractEvent<
    CourseCreatedEvent.InputTuple,
    CourseCreatedEvent.OutputTuple,
    CourseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CourseDeactivated"
  ): TypedContractEvent<
    CourseDeactivatedEvent.InputTuple,
    CourseDeactivatedEvent.OutputTuple,
    CourseDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "CoursePurchased"
  ): TypedContractEvent<
    CoursePurchasedEvent.InputTuple,
    CoursePurchasedEvent.OutputTuple,
    CoursePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "CourseUpdated"
  ): TypedContractEvent<
    CourseUpdatedEvent.InputTuple,
    CourseUpdatedEvent.OutputTuple,
    CourseUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CourseCreated(uint256,string,address,uint256)": TypedContractEvent<
      CourseCreatedEvent.InputTuple,
      CourseCreatedEvent.OutputTuple,
      CourseCreatedEvent.OutputObject
    >;
    CourseCreated: TypedContractEvent<
      CourseCreatedEvent.InputTuple,
      CourseCreatedEvent.OutputTuple,
      CourseCreatedEvent.OutputObject
    >;

    "CourseDeactivated(uint256)": TypedContractEvent<
      CourseDeactivatedEvent.InputTuple,
      CourseDeactivatedEvent.OutputTuple,
      CourseDeactivatedEvent.OutputObject
    >;
    CourseDeactivated: TypedContractEvent<
      CourseDeactivatedEvent.InputTuple,
      CourseDeactivatedEvent.OutputTuple,
      CourseDeactivatedEvent.OutputObject
    >;

    "CoursePurchased(uint256,address,uint256,uint256)": TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;
    CoursePurchased: TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;

    "CourseUpdated(uint256,string,uint256)": TypedContractEvent<
      CourseUpdatedEvent.InputTuple,
      CourseUpdatedEvent.OutputTuple,
      CourseUpdatedEvent.OutputObject
    >;
    CourseUpdated: TypedContractEvent<
      CourseUpdatedEvent.InputTuple,
      CourseUpdatedEvent.OutputTuple,
      CourseUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
