/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { UniversityCourse__factory } from "./UniversityCourse__factory";
export { YCToken__factory } from "./YCToken__factory";
